/*
var intro = "Hi my name is Artem and I am ____ years old.";
var age = 32;
intro = "Hi my name is Artem and I am " + age + " years old.";
console.log(intro);
var num2 = 10;
age + "" + num2;
console.log(age + "" + num2);
var cat1 = "Misty";
var cat2 = "Shadow";
var sentence = "I have two cats, " + cat1 + " and " + cat2 + ".";
var age1 = 3;
var age2 = 5;
sentence = sentence + ". And they are " + age1 + " and " + age2 + " years old.";
console.warn("Warning!");
console.error("Error!");
var test = document.getElementById("test");
var oldText = test.innerHTML;
test.innerHTML = "<strong>Hello, World!</strong>";
var name = document.getElementById("name");
name.innerText = "Artem";
var headline = document.getElementById("headline");
var Myname = "Artem";
headline.innerText = "Hello, " + Myname + "!";
var sentenceNode = document.getElementById("sentence");
var sentence = sentenceNode.innerText;
var upperSentence = sentence.toUpperCase();
sentenceNode.innerText = upperSentence;
var lowerSentence = sentence.toLowerCase();
sentenceNode.innerText = lowerSentence;
var firstTenChars = sentence.substring(0, 10);
var allWords = sentence.split(" ");
var bracketWords = "[" + allWords.join("][") + "]";
var firstThreeWords = allWords.slice(0, 3);
var middleWords = allWords.slice(2, 5);
var makeSentence = middleWords.join(" ");
sentenceNode.innerText = makeSentence;
 */ 
var favoriteColor = prompt("What is your favorite color?");
var customInputNode = document.getElementById("customInput");
customInputNode.innerText = favoriteColor;